#!/bin/bash

NAMES=( "naveen" "prem" "ravi" "siva" ) 

echo "gentel man: ${NAMES[0]}"
echo "powerfull man : ${NAMES[1]}"
echo "talent parson : ${names[2]}"
echo "gamer hero : ${NAMES[3]}"
echo "all names: ${NAMES[@]}"